
spring:
  application:
    name: imooc-
    
  rabbitmq:
    host: 106.14.112.53
    port: 5672
    username: guest
    password: guest
    
  redis:
    host: 106.14.112.53
    port: 6379
    database: 1
    
  datasource:
    #jdbc_config datasource
    driver-class-name: com.mysql.jdbc.Driver
    username: sell
    password: Sell2018$#
    url: jdbc:mysql://106.14.112.53:3306/sell?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull

    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

  jpa:
    show-sql: true
server:
  port: 8875
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8769/eureka-server/eureka
#mybatis
mybatis:
  type-aliases-package: cn.lifuz.imooc.user.model
  type-handlers-package: cn.lifuz.imooc.user.dao
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    cn.lifuz: debug

